sudo: required
services:
  - docker

before_install: 
  - docker build -t prashant/docker-react -f Dockerfile.dev . --progress plain

script: 
  - docker run -e CI=true prashant/docker-react npm run test