sudo: required
services:
  - docker

before_install: 
  - docker build -t prashant/frontend -f Dockerfile.dev . --progress plain

script: 
  - docker run -e CI=true prashant/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  name: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-471112754900"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"